/* eslint-disable import/no-extraneous-dependencies */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './assets/**/*.(js|ts)',
    './templates/**/*.html.twig',
    './src/Components/**/*.php',
    './src/Form/**/*Field.php',
    './src/Builder/**/*.php',
    './src/Entity/**/*.php',
    './node_modules/flowbite/**/*.js',
    './vendor/tales-from-a-dev/flowbite-bundle/templates/**/*.html.twig',
    'config/services.yaml',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        success: '#458e9d',
        warning: '#ffbe19',
        danger: '#e67377',
        secondary: {
          100: '#ecf2f9',
          200: '#d5e4f6',
          300: '#acc8ee',
          400: '#91b5e9',
          500: '#75a3e3',
          600: '#5e82b6',
          700: '#466288',
        },
        neutral: {
          100: '#ffffff',
          200: '#f5f6f7',
          300: '#ebeff5',
          400: '#e1e5ea',
          500: '#cdd3db',
          600: '#8696a9',
          700: '#5d738d',
          800: '#355070',
          900: '#1f2f42',
        },
        corail: {
          100: '#faeceb',
          200: '#ffdad6',
          300: '#ffc8c2',
          400: '#ffada3',
          500: '#ff9184',
          600: '#e5786c',
          700: '#c76357',
        },
        purple: {
          100: '#f4ecf9',
          200: '#e0d4e7',
          300: '#ab92b9',
          400: '#997ea9',
          500: '#866c96',
          600: '#765a87',
          700: '#644578',
        },
      },
    },
    fontFamily: {
      body: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      sans: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'system-ui',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
    },
  },
  safelist: [],
  plugins: [require('flowbite/plugin'), require('@tailwindcss/typography')],
};
